name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - run: sudo dpkg -i $DEB
      - run: tar xvzf $TGZ --strip-components 1 -C $DEST
      - run: ar p $DEB data.tar.gz | tar xvz --strip-components 2 -C $DEST

      - run: bash "$(pwd)/rss.sh"

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     publish_dir: ./src