name: "publish"
on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Rust project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release

      # Tree
      - name: Tree dir
        run: tree /F target/

  # release-tags:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: ncipollo/release-action@v1
  #     with:
  #       artifacts: "release.tar.gz,foo/*.txt"
  #       bodyFile: "body.md"
  #       token: ${{ secrets.GITHUB_TOKEN }}